type SurveyCondition = "Excellent" | "Serviceable" | "Fair" | "Poor" | "N/A" | "Not inspected";
type SurveyRecommendation = "A" | "B" | "C" | "D";

type MdiSurveyItem = {
  section_number: number;
  section_name: string;
  item_number: string;
  description: string;
  condition: SurveyCondition;
  notes: string;
  recommendation_level: SurveyRecommendation | null;
  recommendation_text: string | null;
  photo_urls: string[];
  inspected_status: string;
  test_method: string;
  safety_critical: boolean;
  insurance_critical: boolean;
  compliance_critical: boolean;
  sync_status: string;
  sort_order: number;
  section_data: Record<string, unknown>;
  estimated_cost_eur?: number;
};
export const mdiT9Report = {
  report_type: "pre_purchase",
  vessel_name: "TEST - T9 MDI Survey Rebuild",
  vessel_type: "Motor Yacht",
  manufacturer: "Terranova Yachts",
  model: "T85 M/Y",
  year_built: 2019,
  flag: "Malta",
  hin: "IT-TRHT8509L922",
  lying: "Port Vauban, Antibes, France",
  survey_date: "2025-11-28",
  survey_purpose: "Pre-purchase",
  weather_conditions: "Sunny and calm, wind at 5 kts",
  sea_state: "Calm",
  intended_use: "Private motor yacht",
  survey_scope:
    "General pre-purchase condition survey carried out afloat at berth and during sea trial. No destructive testing, dismantling, code compliance survey, stability assessment, or full machinery survey was carried out.",
  standards_referenced: [
    "Marine Developments International terms and conditions",
    "Good marine survey practice",
    "Visual and functional inspection where accessible",
  ],
  limitations: [
    "No parts of the vessel were dismantled and no fastenings were removed.",
    "Covered or obscured areas behind tanks, linings and bulkheads could not be inspected.",
    "The vessel was not hauled at the survey, therefore the underwater hull, stern gear and anodes were not fully inspected.",
    "Engines, tanks, rudders, stern gear and installed equipment remained in situ and restricted internal access.",
    "Mechanical condition of engines and complete installation is outside the scope of this survey.",
    "Electrical systems were switch-tested only and electronic equipment was not fully assessed.",
    "Tanks and pipework were examined visually from outside only; tanks were not pressure tested or internally inspected.",
    "Seacocks were not removed and there was no hose testing.",
    "The vessel was not surveyed to MCA code, CE/RCD/RCR, machinery directive or local byelaws.",
  ],
  client_name: "Mr Vasilis Moundreas",
  client_email: null,
  client_phone: null,
  surveyor_name: "Captain Henry Topham",
  surveyor_qualification: "Dip.MS",
  surveyor_company: "Marine Developments International",
  surveyor_phone: "+34 664 890 740",
  surveyor_email: null,
  overall_condition:
    "Well designed, comfortable and spacious motor yacht, with multiple urgent and specialist recommendations requiring attention before completion of purchase.",
};

const common = {
  photo_urls: [],
  inspected_status: "Inspected",
  test_method: "Visual inspection and functional check where accessible",
  safety_critical: false,
  insurance_critical: false,
  compliance_critical: false,
  sync_status: "synced",
};

function item(
  section_number: number,
  section_name: string,
  item_number: string,
  description: string,
  condition: SurveyCondition,
  notes: string,
  recLevel: SurveyRecommendation | null = null,
  recText: string | null = null,
  extra: Partial<MdiSurveyItem> = {},
): MdiSurveyItem {
  return {
    ...common,
    section_number,
    section_name,
    item_number,
    description,
    condition,
    notes,
    recommendation_level: recLevel,
    recommendation_text: recText,
    sort_order: Number(String(item_number).split(".")[1] || "0"),
    section_data: {},
    ...extra,
  };
}

export const mdiT9Items = [
  item(1, "Introduction", "1.0", "Client and location", "Serviceable",
    "Acting on the instruction of Mr Vasilis Moundreas, surveyor Henry Topham attended T9, a Terranova motor yacht, at her berth in Port Vauban, Antibes, France. Liability is to the named client only and under Spanish jurisdiction."),
  item(1, "Introduction", "1.1", "Purpose and scope", "Serviceable",
    "The purpose of survey was to assess the vessel's general structural and material condition pre-purchase. No inspection was made for compliance with regulations, codes, local byelaws, stability or performance."),
  item(2, "Specification", "2.0", "Vessel specifications from ships papers", "Not inspected",
    "Specifications were taken from ship's papers, builder information and manuals, and were unverified.",
    null, null, {
      section_data: {
        model: "T85",
        type: "M/Y",
        loa_m: "26.10",
        lwl_m: "22.14",
        beam_m: "7.14",
        draft_m: "3.32",
        displacement: "72.6 t",
        year_of_build: "2019",
        hull_material: "Glass reinforced polyester",
        deck_material: "GRP gelcoat with sandwich core",
        keel: "Full length planing",
        engines: "2 x MAN D2676 LE 443 730 hp",
        transmissions: "ZF 500.1IV i=3 x 2",
        fuel_capacity_l: "9000",
        fresh_water_l: "2460",
        black_water_l: "Holding tank 950",
        grey_water_l: "Holding tank 950",
        registration: "Malta",
        hin: "IT-TRHT8509L922",
      },
    }),
  item(4, "Limitations of Survey", "4.0", "No parts dismantled", "Not inspected",
    "No parts of the vessel were dismantled and no fastenings removed to allow inspection."),
  item(4, "Limitations of Survey", "4.1", "Covered or obscured areas", "Not inspected",
    "Areas covered or obscured by fittings, tanks, linings and bulkheads could not be inspected and cannot be reported as free from defect."),
  item(4, "Limitations of Survey", "4.2", "Owner declarations", "Serviceable",
    "The owner was not present but was represented by Andrei Sevcenco from AA Yachts, Antibes, who advised on recent repairs and replacement."),
  item(4, "Limitations of Survey", "4.3", "Conditions", "Serviceable",
    "Conditions were sunny and calm, wind at 5 kts, calm sea state. Distance observations showed the hull and topsides fair with no undue distortions visible."),
  item(5, "Construction", "5.0", "Hull construction and material", "Serviceable",
    "Glass fibre hull incorporating a full length keel. Hard chine displacement design with spray rails, raked stern and raked bow stem. Precise lay-up was not ascertained."),
  item(5, "Construction", "5.1", "Deck construction", "Serviceable",
    "Deck moulding was composite construction, stiffened across the flats with a sandwich core."),
  item(6, "Hull", "6.0", "Hull inspection afloat", "Not inspected",
    "The vessel was not hauled at the survey and the underwater hull could not be inspected. The vessel had not been hauled for over a year and marine growth was present.",
    "B", "Lift the vessel and pressure wash hull, rudders and stern gear. Replace sacrificial anodes on shafts, propellers and supports. Check cutlass bearings and replace if worn.",
    { insurance_critical: true, estimated_cost_eur: 6000, section_data: { inspection_mode: "Afloat", underwater_findings: "Not hauled; marine growth present" } }),
  item(7, "Rudders and Steering", "7.0", "Rudders, bearings and steering gear", "Serviceable",
    "Two semi-balanced bronze alloy rudders were installed into stern tubes and visible inside crew cabin lockers. Bearings and top seals were in good condition with no water ingress. Steel link bar and hydraulic cylinder fitted. Raymarine position sensor attached to rudder stock."),
  item(7, "Rudders and Steering", "7.1", "Steering stations", "Serviceable",
    "Stainless steel helm wheel at main helm station. Ancillary steering locations alongside helm station and aft deck aided docking and were in good working order."),
  item(8, "Stern Gear", "8.0", "Stern gear inspection", "Not inspected",
    "Stern gear could not be inspected as the vessel was not hauled."),
  item(8, "Stern Gear", "8.1", "Bow and stern thrusters", "Serviceable",
    "Bow thruster and stern thruster were operated from SidePower controllers at the helm and found in good working order. Large three-phase electric motors were fitted."),
  item(8, "Stern Gear", "8.2", "Shaft logs and PSS seals", "Fair",
    "Shaft logs could not be inspected. PSS seals showed salt water contamination at seal faces and were original fittings.",
    "A", "Draw the drive shafts and replace the two PSS units at next haul out. Clean propellers, change anodes, polish and coat with Propspeed antifouling compound or similar.",
    { safety_critical: true, insurance_critical: true, estimated_cost_eur: 12000 }),
  item(9, "Through Hull Fittings and Seacocks", "9.0", "Engine raw water intakes", "Poor",
    "Engine raw water intake seacocks had seized valves on both sides due to lack of use. Pipework and sea chest strainers were generally good except salt water contamination at pipework joints.",
    "A", "Free engine raw water seacock valves and clean raw water pipework to strainers of salt contamination. Work valves every week to prevent future seizure.",
    { safety_critical: true, insurance_critical: true, estimated_cost_eur: 3500 }),
  item(9, "Through Hull Fittings and Seacocks", "9.1", "Air conditioning raw water intake", "Serviceable",
    "Air conditioning raw water seacock was in good working order with freely moving valve, no corrosion on bronze alloy body, and clean sea chest strainer."),
  item(9, "Through Hull Fittings and Seacocks", "9.2", "Generator raw water intakes", "Serviceable",
    "Raw water intakes to both generators were in good condition with freely moving valves, good valve bodies and clean sea chest strainers."),
  item(9, "Through Hull Fittings and Seacocks", "9.3", "Watermaker raw water intake", "Not inspected",
    "Water maker raw water intake lift pump was not tested because the watermaker unit had been removed and was away being repaired."),
  item(10, "Hull Topsides", "10.0", "Topsides condition", "Fair",
    "White gelcoat topsides with blue Awlgrip paint on lower sections. Fair condition with no excessive witness marks and no damage noted. Upper white gelcoat required machine polishing."),
  item(10, "Hull Topsides", "10.1", "Gelcoat cracks", "Fair",
    "Aft deck and access to crew cabins and engine room had visible gelcoat cracks. Further cracks were visible on upper deck port side.",
    "C", "Repair cracked aft doorway and coaming on the upper deck.",
    { estimated_cost_eur: 4000 }),
  item(10, "Hull Topsides", "10.2", "Teak handrails", "Serviceable",
    "Teak handrails running along upper decks were in good order."),
  item(11, "Deck and Fittings", "11.0", "Deck surface and overlay", "Serviceable",
    "Side decks, aft deck and swim platform had teak overlay with grey sealant, all in good condition and well adhered to substrate."),
  item(11, "Deck and Fittings", "11.1", "Foredeck", "Fair",
    "Foredeck non-slip moulded finish was in need of cleaning but in good condition up to the two anchor capstans."),
  item(11, "Deck and Fittings", "11.2", "Guard rails and access doors", "Serviceable",
    "50 mm stainless steel guard rail sat on top of bulwark around deck, in good condition, with side access doors in good working order."),
  item(11, "Deck and Fittings", "11.3", "Anchor and line capstans", "Serviceable",
    "Two Maxwell electric anchor and line capstans at bow with 14 mm chain gypsies and line capstans operated in good working order during docking."),
  item(11, "Deck and Fittings", "11.4", "Aft line capstans", "Serviceable",
    "Aft Maxwell electric line capstans operated with aft lines during docking and were both operational."),
  item(11, "Deck and Fittings", "11.5", "Windscreen, wipers and washers", "Serviceable",
    "Wheelhouse windscreen was in good condition with wipers and washers serviceable from helm control panel."),
  item(11, "Deck and Fittings", "11.6", "Fairleads and cleats", "Serviceable",
    "Stainless steel fairleads and cleats were in good condition and observed operating at dock."),
  item(11, "Deck and Fittings", "11.7", "Fenders and mooring lines", "Serviceable",
    "Fenders and mooring lines were observed during docking and seen to be in good order."),
  item(11, "Deck and Fittings", "11.8", "Tender crane", "Fair",
    "Opecmare deck crane operated but no tender was available to test fully."),
  item(11, "Deck and Fittings", "11.9", "Passerelle", "Serviceable",
    "Hydraulic passerelle installed for access to aft deck and fully operational, with hydraulic power pack in engine bay."),
  item(11, "Deck and Fittings", "11.10", "Flybridge mast and lights", "Serviceable",
    "Flybridge had no steering or engine control fitted but had radar mast with anchor and steaming lights."),
  item(11, "Deck and Fittings", "11.11", "Anchors and chain", "Serviceable",
    "Two galvanised 14 mm chains of unknown length were attached to two galvanised Fortress type anchors in good visual condition."),
  item(12, "Hatches and Port Lights", "12.0", "Deck hatches", "Serviceable",
    "Lewmar deck mounted hatches with toughened glass vision panels fitted to foredeck were in good working order."),
  item(12, "Hatches and Port Lights", "12.1", "Cabin portlights", "Fair",
    "Cabin portlights were generally good except starboard side twin cabin had water ingress which compromised internal fibreboard; board finish was blown.",
    "C", "Replace damaged portlight board in twin cabin and reseal the portlight.",
    { estimated_cost_eur: 1800 }),
  item(12, "Hatches and Port Lights", "12.2", "Saloon side lights and opening windows", "Serviceable",
    "Saloon side lights and opening windows were all in good working order with no evidence of water ingress."),
  item(13, "Ventilation", "13.0", "Air conditioning chillers", "Serviceable",
    "Climma air conditioning chillers were tested with Kohler generator and shore power and were running as designed."),
  item(13, "Ventilation", "13.1", "Air handlers", "Fair",
    "Climma air handlers in cabins were being maintained by a local company to improve drainage and operation at time of survey."),
  item(14, "Canvas and Covers", "14.0", "Saloon and dinette cushions", "Serviceable",
    "Saloon seats and dinette seating cushions were all in good condition."),
  item(14, "Canvas and Covers", "14.1", "Cabin mattresses and seat covers", "Serviceable",
    "Cabin mattresses and seat covers were in good order throughout."),
  item(15, "Engines and Transmissions", "15.0", "Engine condition and installation", "Serviceable",
    "Two MAN D2676 LE 443 six-cylinder diesel engines, serial numbers P5105658135650 and S5105658055650, were installed and tested at sea trial, found operational.",
    null, null, { section_data: { engine_make: "MAN", engine_model: "D2676 LE 443", port_serial_number: "P5105658135650", starboard_serial_number: "S5105658055650", horsepower: "730", start_test: "Started easily" } }),
  item(15, "Engines and Transmissions", "15.1", "Engine mountings", "Serviceable",
    "Resilient engine mountings were inspected and found securely fitted to bearers and longitudinal stringers."),
  item(15, "Engines and Transmissions", "15.2", "Exhaust system", "Fair",
    "Engine exhaust pipework was free of defects with good stainless steel insulation and pipework. Exhaust elbows attached to mufflers were fair with rust forming at welds."),
  item(15, "Engines and Transmissions", "15.3", "Air filters, turbochargers, belts", "Serviceable",
    "Air filters and turbochargers were in good working order when tested; belts and paintwork were in good condition."),
  item(15, "Engines and Transmissions", "15.4", "Gearboxes and transmissions", "Serviceable",
    "ZF 500-11v gearboxes installed with serial numbers P20370397 and S20370396, differing from specification sheet. Gear oil clean and clear; paintwork good; no oil leaks."),
  item(15, "Engines and Transmissions", "15.5", "Fuel system and filters", "Serviceable",
    "Fuel system was in good order with Racor double filter/separators, good pipework and clamps."),
  item(15, "Engines and Transmissions", "15.6", "Fuel tanks", "Poor",
    "Steel painted fuel tanks in engine bay had leaking inspection plates on both tanks; fuel was leaking into bilge but not at an alarming rate.",
    "A", "Reseal the two fuel tank inspection plates to stop diesel fuel leaks.",
    { safety_critical: true, insurance_critical: true, estimated_cost_eur: 4500 }),
  item(15, "Engines and Transmissions", "15.7", "Day tanks", "Not inspected",
    "Day tanks were fitted but could not be checked due to access difficulties."),
  item(15, "Engines and Transmissions", "15.8", "Fuel transfer pump", "Not inspected",
    "Fuel transfer pump between the two fuel tanks was fitted but not tested."),
  item(16, "Internal Structure and Bilges", "16.0", "Bulkheads and tabbing", "Serviceable",
    "Bulkheads and athwartships reinforcement bonded to hull with GRP. Tabbing in good order where sighted, with no cracks or separation."),
  item(16, "Internal Structure and Bilges", "16.1", "Stem and chain locker", "Serviceable",
    "Stem was solid where sighted in chain locker with no faults detected."),
  item(16, "Internal Structure and Bilges", "16.2", "Frames and stringers", "Serviceable",
    "Transverse framing and longitudinal stringers were in good condition where sighted in engine bay and under companionway sole."),
  item(16, "Internal Structure and Bilges", "16.3", "Engine bay bilge pump float switch", "Fair",
    "Engine bay bilge pump had a loose float switch detached from its mounting. Pump was operational.",
    "A", "Refit the engine bay float switch to the mounting plate.",
    { safety_critical: true, insurance_critical: true, estimated_cost_eur: 500 }),
  item(16, "Internal Structure and Bilges", "16.4", "Aft bilge pump", "Serviceable",
    "Aft bilge pump was in good working order on manual and automatic."),
  item(17, "Accommodation and Domestic", "17.0", "Forepeak cabin", "Serviceable",
    "Forepeak cabin had double berth with ensuite bathroom, fresh water flushing head, hand basin and shower, all in good condition."),
  item(17, "Accommodation and Domestic", "17.1", "Midships twin cabins", "Serviceable",
    "Two midships twin cabins had twin berths and ensuite bathrooms with freshwater flushing heads, basins and showers; all serviceable."),
  item(17, "Accommodation and Domestic", "17.2", "Master cabin", "Serviceable",
    "Aft master cabin had double berth and ensuite bathroom, all in good condition."),
  item(17, "Accommodation and Domestic", "17.3", "Galley and appliances", "Serviceable",
    "Galley had Miele four-burner induction hob, Miele oven, refrigerators and freezers in operational condition, plus Miele microwave."),
  item(17, "Accommodation and Domestic", "17.4", "Dining room and saloon", "Serviceable",
    "Dining room forward of galley and saloon had wood table and loose chairs in good condition."),
  item(17, "Accommodation and Domestic", "17.5", "Laundry", "Not inspected",
    "Miele washer and dryer located in separate room forward of lower deck twin cabins, untested."),
  item(17, "Accommodation and Domestic", "17.6", "Interior and exterior trims", "Fair",
    "Ceiling panel trim aft of saloon had cracked finish. External flybridge ceiling panel was also cracked and broken.",
    "C", "Replace cracked trims in the saloon and aft deck ceiling.",
    { estimated_cost_eur: 3500 }),
  item(19, "Electrical System and Generators", "19.0", "Shore power and AC distribution", "Serviceable",
    "400 V AC three-phase shore power supply entered aft coaming and fed distribution transformer. Voltage was rectified/reduced for chargers and DC equipment; 400 V AC supplied thrusters and other AC equipment."),
  item(19, "Electrical System and Generators", "19.1", "DC battery bank", "Serviceable",
    "24 V DC supplied vessel equipment via DC service battery bank located under engine bay sole."),
  item(19, "Electrical System and Generators", "19.2", "Switchboards", "Serviceable",
    "Control switchboards were located in engine bay and at helm station, with switches and indicators in good working order."),
  item(19, "Electrical System and Generators", "19.3", "Generators condition", "Fair",
    "Two Kohler three-phase generators installed in engine bay. Starboard generator had defective impeller being changed and could not be tested."),
  item(19, "Electrical System and Generators", "19.4", "Port generator exhaust elbow", "Poor",
    "Port side Kohler generator had leaking exhaust elbow previously patched with two-pack filler that had failed, leaking rusty water into bilge from water-cooled muffler.",
    "A", "Repair or replace the port side generator exhaust elbow.",
    { safety_critical: true, insurance_critical: true, estimated_cost_eur: 3000 }),
  item(20, "Fire and Safety Equipment", "20.0", "Fixed fire suppression", "Poor",
    "Fireban suppression system in engine bay had been disconnected and Fireban control panel had no active power supply at survey.",
    "A", "Service Fireban fire system and reconnect the two boxes in the engine bay.",
    { safety_critical: true, insurance_critical: true, compliance_critical: true, estimated_cost_eur: 2500 }),
  item(20, "Fire and Safety Equipment", "20.1", "Portable extinguishers", "Poor",
    "Handheld extinguishers around the vessel had expired service dates.",
    "A", "Service handheld fire extinguishers.",
    { safety_critical: true, compliance_critical: true, estimated_cost_eur: 800 }),
  item(20, "Fire and Safety Equipment", "20.2", "Life rafts", "Fair",
    "Two life rafts on foredeck dated 2022 had no service dates; two on flybridge had service dates of 05/2026.",
    "A", "Service the two foredeck liferafts and verify certification of all liferafts.",
    { safety_critical: true, compliance_critical: true, estimated_cost_eur: 1800 }),
  item(20, "Fire and Safety Equipment", "20.3", "Flares and pyrotechnics", "Serviceable",
    "Solas B flare pack had expiry dates of 02/2028."),
  item(20, "Fire and Safety Equipment", "20.4", "Life vests", "Serviceable",
    "Foam life vests were stowed around vessel cabins."),
  item(20, "Fire and Safety Equipment", "20.5", "EPIRB", "Poor",
    "No EPIRB was sighted.",
    "A", "Fit or locate and certify EPIRB suitable for vessel operation.",
    { safety_critical: true, compliance_critical: true, estimated_cost_eur: 900 }),
  item(21, "Navigation Equipment", "21.0", "Chartplotters, radar and AIS", "Serviceable",
    "Two Raymarine plotters installed at helm station overlaid with Raymarine radar. AIS displayed and switchable between plotters."),
  item(21, "Navigation Equipment", "21.1", "Autopilot", "Serviceable",
    "Raymarine autopilot installed and tested operational at sea trial."),
  item(21, "Navigation Equipment", "21.2", "Depth sounder", "Poor",
    "No depth information was available on any display, presumably due to transducer fault.",
    "A", "Repair depth data fault.",
    { safety_critical: true, insurance_critical: true, estimated_cost_eur: 1500 }),
  item(21, "Navigation Equipment", "21.3", "VHF radio", "Serviceable",
    "Raymarine VHF radio with DSC was available and in good working order."),
  item(21, "Navigation Equipment", "21.4", "Navigation lights", "Poor",
    "Port side navigation light was operational but starboard light was not operating. Anchor and steaming lights functioned.",
    "A", "Repair the starboard navigation light.",
    { safety_critical: true, compliance_critical: true, estimated_cost_eur: 600 }),
  item(22, "Miscellaneous Equipment", "22.0", "Stabiliser system", "Fair",
    "Stabilisation fin system was installed and tested at sea trial. It did not appear to operate as well as expected and requires servicing.",
    "B", "Service the stabiliser system and test.",
    { estimated_cost_eur: 5000 }),
  item(22, "Miscellaneous Equipment", "22.3", "Ship's horn", "Poor",
    "Ship's horn was turned on for test but operated without being switched and requires service.",
    "A", "Service the ship's horn.",
    { safety_critical: true, compliance_critical: true, estimated_cost_eur: 700 }),
  item(23, "Comments and Recommendations", "23.0", "General surveyor comment", "Fair",
    "T9 was a very well designed, comfortable and spacious motor yacht. Given her youth she had many faults requiring repair in several areas. She performed well at sea trial and would have performed better had she been antifouled this year."),
];

export const mdiT9SeaTrial = {
  trial_date: "2025-11-28",
  location: "Antibes",
  weather: "Sunny and calm",
  sea_state: "Calm to choppy in own wash",
  narrative:
    "The engines started easily with no excessive smoke or vibration. Engines performed well through the range of revolutions. Bow and stern thrusters by SidePower operated well and were efficient and powerful. Raymarine autopilot operated in both directions. Depth information was missing from all displays. Stabilisers were activated after the vessel had created her own wash but were less than stable in choppy sea state. Radar displayed successfully on Raymarine plotter with AIS. Screen wipers were operational. Lack of antifouling was considered responsible for slower speed readings at given RPM.",
  tickover_rpm: 600,
  tickover_speed: 3.1,
  max_rpm: 2000,
  max_speed: 13.2,
  rpm_table: [
    { rpm: 1000, coolant_p: 80, coolant_s: 80, oil_p: 3.0, oil_s: 2.9, speed: 7.3 },
    { rpm: 1500, coolant_p: 86, coolant_s: 85, oil_p: 4.3, oil_s: 4.4, speed: 10.4 },
    { rpm: 2000, coolant_p: 87, coolant_s: 87, oil_p: 4.8, oil_s: 5.0, speed: 13.0 },
    { rpm: 2000, coolant_p: 86, coolant_s: 87, oil_p: 4.8, oil_s: 4.6, speed: 13.2 },
  ],
  additional_observations:
    "Depth information missing from displays. Stabilisers require service. Ship's horn requires service. Autopilot, radar, AIS and wipers tested operational.",
};



